name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup dotnet env
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: '7.0.x'
            include-prerelease: true
        
      - name: Build
        run: dotnet build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sh /home/comunidades/poc_deploy.sh
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_USER_PASSWORD }}
          port: ${{ secrets.PRODUCTION_SSH_PORT }}
